# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsubio" do
  name "bsubio"
  desc "CLI for easy running heavy duty compute jobs in the cloud"
  homepage "https://www.bsub.io"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsubio"

  on_macos do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "4776726e52cc3ece9b0377596c52d67fc56e33c3024dbac44cb4559a0095321c"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "c59e129e5264b55b866223e56b40d76a8d5b12fe13ec88ad2c28f60ce43a562f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "46c8ddbd47586822e3108d311f938bbda310de1b128e63c5213013ca789cff77"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "66ab98ba1a6d5d443c8ed6d6d01fa39d2929fe4d591067509cf3a80b1cb444bc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsubio"]
    end
  end

  # No zap stanza required
end
