# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsubio" do
  name "bsubio"
  desc "CLI for easy running heavy duty compute jobs in the cloud"
  homepage "https://www.bsub.io"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsubio"

  on_macos do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "1221d454d01fcaffbe60725b177f7d99ef48c107903e4c7bf8b170dfde57e5ba"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "5fafe004c396d9d2c0715fe2d8b701f95789ec8a8bab68c3cd5e3344189be2b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "cb3b966b924b90cc16a83073b8e3eced1744ac99b54c951b3d3282bee0769e1d"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "1cb17351b20cefd020f9e4e9997f32237f68b2a84819748f81385576d2218efd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsubio"]
    end
  end

  # No zap stanza required
end
