# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsubio" do
  name "bsubio"
  desc "CLI for easy running heavy duty compute jobs in the cloud"
  homepage "https://bsub.io"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsubio"

  on_macos do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "e2ec6eb7636f59b26688c6cc91503cc8922ba1f12ad924df675a31965c3ebfa9"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "2849505b3cca26eaa70ebae5ce1bc9378cd9681b7bad8db7ec77f68ea173d835"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "27d87fd68ff0f5589f4609b2926a5104619fef2ed0c593d6fb95b0cf236793ea"
    end
    on_arm do
      url "https://github.com/bsubio/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bsubio/cli/"
      sha256 "41db235830fd29be7733886e3e364456c884efed23400cd0ec4b1091b68212be"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsubio"]
    end
  end

  # No zap stanza required
end
